# This file will NOT be automatically included if you define COMPOSE_FILE in .env
# You need to explicity include it in the list COMPOSE_FILE files.
version: '3'
services:
  app:
    ports:
      - "43447:43447"

