#
# This is a docker-compose overlay that creates a solr
# service (solr-test) for use with rspec and cucumber testing.
# 
version: '2'
services:
  app:
    environment:
      TEST_SOLR_HOST: solr-test
      TEST_SOLR_PORT: 8981
  solr-test:
    image: concordconsortium/docker-solr-portal
    environment:
      TEST_SOLR_PORT: 8981
    #
    # Mount the portal source in the container under /rigse
    #
    volumes:
      - .:/rigse
    #
    # Invoke the docker/dev/start-solr-test.sh script allowing us
    # to specify a port and other parameters.
    #
    command: ["/bin/bash", "-c", "/rigse/docker/dev/start-solr-test.sh -f -p $${TEST_SOLR_PORT}" ]
