--- 
active_school_levels: &id001 
  - "2"
  - "3"
  - "4"
active_grades: &id002 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
development: &id003
  active_school_levels: *id001
  help_email: skim@concord.org
  theme: sparks
  active_grades: *id002
  site_school: SPARKS-school
  description: ""
  site_district: SPARKS-district
  site_name: SPARKS Assessments (development)
  default_admin_user: 
    first_name: Seong
    login: skim
    last_name: Kim
    email: skim@concord.org
  states_and_provinces: 
  - VA
test: *id003
production: *id003
staging: *id003
cucumber: *id003

--- 
development: 
  site_url: http://localhost:3000
  active_school_levels: &id001 
    - "2"
    - "3"
    - "4"
  maven_jnlp_servers: &id002 
    - :path: /dev/org/concord/maven-jnlp/
      :name: concord
      :host: http://jnlp.concord.org
  active_grades: &id003 
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  default_maven_jnlp: 
    version: snapshot
    server: concord
    family: all-otrunk-snapshot
  site_school: RITES Investigations-school
  valid_sakai_instances: &id004 
    - http://moleman.concord.org/
    - http://test.porfolio.ri.net/
    - http://portfolio.ri.net
    - https://test.portfolio.ri.net/
    - https://portfolio.ri.net/
  maven_jnlp_families: 
  - all-otrunk-snapshot
  site_district: RITES Investigations-district
  description: 
  site_name: RITES Investigations (development)
  enable_default_users: true
  default_admin_user: 
    first_name: Stephen
    login: stephen
    last_name: Bannasch
    email: stephen.bannasch@gmail.com
  states_and_provinces: 
  - RI
  - MA
  :default_maven_jnlp: 
    version: snapshot
    server: concord
    family: all-otrunk-snapshot
test: 
  site_url: http://localhost:3000
  active_school_levels: *id001
  maven_jnlp_servers: *id002
  active_grades: *id003
  default_maven_jnlp: 
    version: snapshot
    server: concord
    family: all-otrunk-snapshot
  site_school: RITES Investigations-school
  valid_sakai_instances: *id004
  description: ""
  site_district: RITES Investigations-district
  enable_default_users: true
  site_name: RITES Investigations (development)
  default_admin_user: 
    first_name: Stephen
    login: stephen
    last_name: Bannasch
    email: stephen.bannasch@gmail.com
  states_and_provinces: 
  - RI
  - MA
production: 
  site_url: http://rites-investigations.concord.org
  active_school_levels: *id001
  help_email: rites-investigations@concord.org
  maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  theme: rites
  active_grades: 
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  default_maven_jnlp: 
    version: 0.1.0-20090724.190238-a
    server: concord
    family: all-otrunk-snapshot
  site_school: RITES Investigations-school
  valid_sakai_instances: 
  - https://portfolio.ri.net/
  maven_jnlp_families: 
  - all-otrunk-snapshot
  site_district: RITES Investigations-district
  description: ""
  site_name: RITES Investigations
  enable_default_users: true
  default_admin_user: 
    first_name: Stephen
    login: stephen
    last_name: Bannasch
    email: stephen.bannasch@gmail.com
  states_and_provinces: 
  - RI
  - MA
  :default_maven_jnlp: 
    version: 0.1.0-20090724.190238-a
    server: concord
    family: all-otrunk-snapshot
staging: 
  site_url: http://rites.dev.concord.org
  active_school_levels: *id001
  maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  active_grades: 
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  default_maven_jnlp: 
    version: 0.1.0-20090724.190238
    server: concord
    family: all-otrunk-snapshot
  site_school: RITES Investigations-school
  valid_sakai_instances: 
  - http://localhost:3000/
  site_district: RITES Investigations-district
  description: ""
  site_name: RITES Investigations (staging)
  enable_default_users: true
  default_admin_user: 
    first_name: Stephen
    login: stephen
    last_name: Bannasch
    email: stephen.bannasch@gmail.com
  states_and_provinces: 
  - RI
  - MA
cucumber: 
  active_school_levels: *id001
  site_url: http://localhost:3000
  maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  active_grades: 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  default_maven_jnlp: 
    version: snapshot
    server: concord
    family: all-otrunk-snapshot
  valid_sakai_instances: *id004
  maven_jnlp_families: 
  - all-otrunk-snapshot
  site_school: RITES Investigations-school
  include_otrunk_examples: false
  site_district: RITES Investigations-district
  description: ""
  enable_default_users: true
  default_admin_user: 
    first_name: Stephen
    login: stephen
    last_name: Bannasch
    email: stephen.bannasch@gmail.com
  site_name: RITES Investigations (development)
  states_and_provinces: 
  - RI
