sudo: false # see: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: ruby
rvm:
  - "1.9.3"
env:
  - RAILS_ENV=test TEST_SUITE=spec
  - RAILS_ENV=cucumber TEST_SUITE=cucumber

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/app_environment_variables.sample.rb config/app_environment_variables.rb
  - cp config/settings.sample.yml config/settings.yml
  - cp config/sis_import_data.sample.yml config/sis_import_data.yml
  - cp config/initializers/site_keys.rb.sample config/initializers/site_keys.rb
  - mysql -e "create database rigse_test;"
  - bundle exec spring rake db:schema:load
  - bundle exec spring rake db:migrate
  - bundle exec spring rake db:test:prepare

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec spring rake $TEST_SUITE

cache: bundler

bundler_args: --without development

# blacklist - these branches aren't feature branches and shouldn't be getting direct commits
# branches:
#   except:
#     - staging
#     - production
