# This file will NOT be automatically included if you define COMPOSE_FILE in .env
# You need to explicity include it in the list COMPOSE_FILE files.
version: '3'
services:

  app:
    ports:
      - "3000:3000"

      #
      # Expose this port to view cucumber firefox tests with a vnc client
      #
      # - "5900:5900"

  solr:
    ports:
      - "8983:8983"

