version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: script/docker-app.sh
    environment:
      DB_HOST: 10.0.0.2
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: portal_production
      SOLR_HOST: solr
      SOLR_PORT: 8983
    networks:
      - appnet
    ports:
      - "3000:3000"
    volumes:
      - .:/rigse
      - "bundle:/bundle"
  solr:
    image: solr
    networks:
      - appnet
    ports:
      - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    depends_on:
      - solrdata
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  solrdata:
    image: solr
    volumes:
      - data:/opt/solr/server/solr/mycores
    user:
      root
    entrypoint:
      - chown
      - solr:solr
      - /opt/solr/server/solr/mycores
networks:
  appnet:
volumes:
  bundle:
  data:
