--- 
- otrunk_object_class: org.concord.data.state.OTLinearProducerFilter
  name: Linear Filter
  k0_active: true
  k2_active: false
  k1_active: true
  uuid: 
  id: 1
  description: "The Linear Filter applies a two-point linear transformation to the input data: Y = k0 + k1 * X."
  previous_user_id: 
  k3_active: false
  user_id: 
- otrunk_object_class: org.concord.data.state.OTIntegratingProducerFilter
  name: Integrating Filter
  k0_active: false
  k2_active: false
  k1_active: false
  uuid: 
  id: 2
  description: The Integrating Filter applies a simple integration filter to the input data. This filter takes no parameters.
  previous_user_id: 
  k3_active: false
  user_id: 
- otrunk_object_class: org.concord.data.state.OTDifferentiatingProducerFilter
  name: Differentiating Filter
  k0_active: false
  k2_active: false
  k1_active: false
  uuid: 
  id: 3
  description: "Take the derivative of the values.  "
  previous_user_id: 
  k3_active: false
  user_id: 
