--- 
- si: true
  name: Celsius
  quantity: temperature
  uuid: 
  id: 1
  description: Celsius is a unit of temperature.
  unit_symbol_text: degC
  previous_user_id: 
  base_unit: false
  user_id: 2
  unit_symbol: "\xC2\xB0C"
- si: true
  name: meter
  quantity: length
  uuid: 
  id: 2
  description: Meters are a standard SI unit of length.
  unit_symbol_text: m
  previous_user_id: 
  base_unit: true
  user_id: 2
  unit_symbol: m
- si: true
  name: meters per second
  quantity: velocity
  uuid: 
  id: 3
  description: Meters per second is a standard SI unit for velocity.
  unit_symbol_text: m/s
  previous_user_id: 
  base_unit: false
  user_id: 13
  unit_symbol: m/s
- si: false
  name: "revolutions per second "
  quantity: " rotational speed"
  uuid: 
  id: 4
  description: "rotational speed -- not angular velocity which would be degrees or radians per second. "
  unit_symbol_text: S
  previous_user_id: 
  base_unit: false
  user_id: 13
  unit_symbol: S
