--- 
- name: Temperature
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: degC
  max: 40.0
  uuid: 1fd25c46-4163-11de-aad1-001ff3caa767
  port: 0
  id: 1
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 0
  created_at: 2009-05-15 13:20:30 Z
- name: Light
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: lux
  max: 4000.0
  uuid: 202233ce-4163-11de-aad1-001ff3caa767
  port: 0
  id: 2
  display_precision: 0
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 2
  created_at: 2009-05-15 13:20:30 Z
- name: Pressure
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: kPa
  max: 104.0
  uuid: 2022efee-4163-11de-aad1-001ff3caa767
  port: 0
  id: 3
  display_precision: -1
  min: 96.0
  user_id: 9
  step_size: 0.1
  ptype: 3
  created_at: 2009-05-15 13:20:30 Z
- name: Voltage
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: V
  max: 10.0
  uuid: 2023bdb6-4163-11de-aad1-001ff3caa767
  port: 0
  id: 4
  display_precision: -2
  min: -10.0
  user_id: 9
  step_size: 0.1
  ptype: 4
  created_at: 2009-05-15 13:20:30 Z
- name: Force (5N)
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.01
  unit: N
  max: 4.0
  uuid: 20263140-4163-11de-aad1-001ff3caa767
  port: 0
  id: 5
  display_precision: -2
  min: -4.0
  user_id: 9
  step_size: 0.01
  ptype: 5
  created_at: 2009-05-15 13:20:30 Z
- name: Force (50N)
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.01
  unit: N
  max: 40.0
  uuid: 2026e04a-4163-11de-aad1-001ff3caa767
  port: 0
  id: 6
  display_precision: -1
  min: -40.0
  user_id: 9
  step_size: 0.1
  ptype: 5
  created_at: 2009-05-15 13:20:30 Z
- name: Distance
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: m
  max: 4.0
  uuid: 20276f7e-4163-11de-aad1-001ff3caa767
  port: 0
  id: 7
  display_precision: -2
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 13
  created_at: 2009-05-15 13:20:30 Z
- name: Relative Humidity
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: percentage
  max: 90.0
  uuid: 2027e9ea-4163-11de-aad1-001ff3caa767
  port: 0
  id: 8
  display_precision: -1
  min: 10.0
  user_id: 9
  step_size: 0.1
  ptype: 7
  created_at: 2009-05-15 13:20:30 Z
- name: CO2
  updated_at: 2009-05-15 17:20:30 Z
  period: 1.0
  unit: ppm
  max: 500.0
  uuid: 20286398-4163-11de-aad1-001ff3caa767
  port: 0
  id: 9
  display_precision: 2
  min: 0.0
  user_id: 9
  step_size: 20.0
  ptype: 18
  created_at: 2009-05-15 13:20:30 Z
- name: Oxygen Gas
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: ppt
  max: 300.0
  uuid: 2028dcf6-4163-11de-aad1-001ff3caa767
  port: 0
  id: 10
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 19
  created_at: 2009-05-15 13:20:30 Z
- name: pH
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: pH
  max: 14.0
  uuid: 20295af0-4163-11de-aad1-001ff3caa767
  port: 0
  id: 11
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 20
  created_at: 2009-05-15 13:20:30 Z
- name: Salinity
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: ppt
  max: 50.0
  uuid: 202a39de-4163-11de-aad1-001ff3caa767
  port: 0
  id: 12
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 21
  created_at: 2009-05-15 13:20:30 Z
- name: Raw Data
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: raw
  max: 10000.0
  uuid: 202adb78-4163-11de-aad1-001ff3caa767
  port: 0
  id: 13
  display_precision: 0
  min: -10000.0
  user_id: 9
  step_size: 1.0
  ptype: 22
  created_at: 2009-05-15 13:20:30 Z
- name: Raw Voltage
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: V
  max: 10.0
  uuid: 202b81fe-4163-11de-aad1-001ff3caa767
  port: 0
  id: 14
  display_precision: -2
  min: -1.0
  user_id: 9
  step_size: 0.01
  ptype: 23
  created_at: 2009-05-15 13:20:30 Z
- name: Sound Level
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: dB
  max: 120.0
  uuid: 202c226c-4163-11de-aad1-001ff3caa767
  port: 0
  id: 15
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 1.0
  ptype: 14
  created_at: 2009-05-15 13:20:30 Z
- name: Magnetic Field
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: G
  max: 10.0
  uuid: 202ca3ea-4163-11de-aad1-001ff3caa767
  port: 0
  id: 16
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 26
  created_at: 2009-05-15 13:20:30 Z
- name: Spirometer
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: L/s
  max: 15.0
  uuid: 202d22f2-4163-11de-aad1-001ff3caa767
  port: 0
  id: 17
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 27
  created_at: 2009-05-15 13:20:30 Z
- name: Heart Rate Signal
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: v
  max: 4.0
  uuid: 202da02e-4163-11de-aad1-001ff3caa767
  port: 0
  id: 18
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 28
  created_at: 2009-05-15 13:20:30 Z
- name: EKG
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.01
  unit: v
  max: 10.0
  uuid: 202e816a-4163-11de-aad1-001ff3caa767
  port: 0
  id: 19
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 29
  created_at: 2009-05-15 13:20:30 Z
- name: Blood Pressure
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: mm Hg
  max: 200.0
  uuid: 202f1b98-4163-11de-aad1-001ff3caa767
  port: 0
  id: 20
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 1.0
  ptype: 30
  created_at: 2009-05-15 13:20:30 Z
- name: Conductivity
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: MICS
  max: 100.0
  uuid: 202f96ea-4163-11de-aad1-001ff3caa767
  port: 0
  id: 21
  display_precision: -1
  min: 0.0
  user_id: 9
  step_size: 1.0
  ptype: 31
  created_at: 2009-05-15 13:20:30 Z
- name: Dissolved Oxygen
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: mg/L
  max: 10.0
  uuid: 20300ca6-4163-11de-aad1-001ff3caa767
  port: 0
  id: 22
  display_precision: -2
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 32
  created_at: 2009-05-15 13:20:30 Z
- name: Acceleration
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: m/s^2
  max: 20.0
  uuid: 20307d6c-4163-11de-aad1-001ff3caa767
  port: 0
  id: 23
  display_precision: -2
  min: 0.0
  user_id: 9
  step_size: 0.1
  ptype: 8
  created_at: 2009-05-15 13:20:30 Z
- name: Colorimeter
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: "%T"
  max: 100.0
  uuid: 2030ebbc-4163-11de-aad1-001ff3caa767
  port: 0
  id: 24
  display_precision: 0
  min: 0.0
  user_id: 9
  step_size: 0.057
  ptype: 33
  created_at: 2009-05-15 13:20:30 Z
- name: Hand Dynamometer
  updated_at: 2009-05-15 17:20:30 Z
  period: 0.1
  unit: N
  max: 400.0
  uuid: 203166fa-4163-11de-aad1-001ff3caa767
  port: 0
  id: 25
  display_precision: 0
  min: 0.0
  user_id: 9
  step_size: 0.35
  ptype: 34
  created_at: 2009-05-15 13:20:30 Z
