--- 
development: &development
  runnables_use: browser
  runnable_mime_type: run_html
  active_school_levels:
    - "2"
    - "3"
    - "4"
  active_grades:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  use_gse: false
  include_otrunk_examples: false
  help_email: stephen.bannasch@gmail.com
  theme: smartgraphs
  top_level_container_name: page
  site_school: SmartGraphs School
  description: ""
  site_district: Smart Graphs District
  site_name: SmartGraphs
  site_url: http://localhost:3000
  enable_default_users: true
  default_admin_user: 
    first_name: Stephen
    last_name: Bannasch
    login: stephen
    email: stephen.bannasch@gmail.com
  states_and_provinces: 
  - MA
test: *development
staging: *development
cucumber: *development
production: *development
