--- 
production:
  :qucs_url: http://otto.concord.org/qucs/index.php 
  :default_admin_user: 
    :login: skim
    :last_name: Kim
    :email: skim@concord.org
    :first_name: Seong
  :site_name: SPARKS Assessments
  :active_grades: 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  :top_level_container_name: page
  :runnable_mime_type: run_sparks_html
  :enable_default_users: false
  :include_otrunk_examples: false
  :site_url: http://sparks.portal.concord.org
  :theme: sparks
  :net_logo_package_name: otrunknl4
  :site_district: SPARKS-district
  :runnables_use: browser
  :site_school: SPARKS-school
  :states_and_provinces: 
  - VA
  :default_maven_jnlp: 
    :server: concord
    :family: all-otrunk-snapshot
    :version: snapshot
  :description: ""
  :maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  :use_gse: false
  :active_school_levels: 
  - "2"
  - "3"
  - "4"
  :maven_jnlp_families: 
  - all-otrunk-snapshot
  :help_email: skim@concord.org
development: 
  :qucs_url: http://otto.concord.org/qucs/index.php
  :default_admin_user: 
    :login: skim
    :last_name: Kim
    :email: skim@concord.org
    :first_name: Seong
  :site_name: SPARKS Assessments (local development)
  :active_grades: 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  :top_level_container_name: page
  :runnable_mime_type: run_sparks_html
  :enable_default_users: true
  :include_otrunk_examples: false
  :site_url: http://localhost:3000
  :theme: sparks
  :net_logo_package_name: otrunknl4
  :site_district: SPARKS-district
  :runnables_use: browser
  :site_school: SPARKS-school
  :states_and_provinces: 
  - VA
  :default_maven_jnlp: 
  :description: 
  :maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  :use_gse: false
  :active_school_levels: 
  - "2"
  - "3"
  - "4"
  :maven_jnlp_families: 
  - all-otrunk-snapshot
  :help_email: skim@concord.org
cucumber:
  :qucs_url: http://otto.concord.org/qucs/index.php 
  :default_admin_user: 
    :login: skim
    :last_name: Kim
    :email: skim@concord.org
    :first_name: Seong
  :site_name: SPARKS Assessments (local development)
  :active_grades: 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  :top_level_container_name: page
  :runnable_mime_type: run_sparks_html
  :enable_default_users: true
  :include_otrunk_examples: false
  :site_url: http://localhost:3000
  :theme: sparks
  :net_logo_package_name: otrunknl4
  :site_district: SPARKS-district
  :runnables_use: browser
  :site_school: SPARKS-school
  :states_and_provinces: 
  - VA
  :default_maven_jnlp: 
    :server: concord
    :family: all-otrunk-snapshot
    :version: snapshot
  :description: ""
  :maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  :use_gse: false
  :active_school_levels: 
  - "2"
  - "3"
  - "4"
  :maven_jnlp_families: 
  - all-otrunk-snapshot
  :help_email: skim@concord.org
staging:
  :qucs_url: http://otto.concord.org/qucs/index.php 
  :default_admin_user: 
    :login: skim
    :last_name: Kim
    :email: skim@concord.org
    :first_name: Seong
  :site_name: SPARKS Assessments (staging)
  :active_grades: 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  :top_level_container_name: page
  :runnable_mime_type: run_sparks_html
  :enable_default_users: true
  :include_otrunk_examples: false
  :site_url: http:/sparks.staging.concord.org
  :theme: sparks
  :net_logo_package_name: otrunknl4
  :site_district: SPARKS-district
  :runnables_use: browser
  :site_school: SPARKS-school
  :states_and_provinces: 
  - VA
  :default_maven_jnlp: 
  :description: ""
  :maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  :use_gse: false
  :active_school_levels: 
  - "2"
  - "3"
  - "4"
  :maven_jnlp_families: 
  - all-otrunk-snapshot
  :help_email: skim@concord.org
test:
  :qucs_url: http://otto.concord.org/qucs/index.php 
  :default_admin_user: 
    :login: skim
    :last_name: Kim
    :email: skim@concord.org
    :first_name: Seong
  :site_name: SPARKS Assessments (local development)
  :active_grades: 
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  :top_level_container_name: page
  :runnable_mime_type: run_sparks_html
  :enable_default_users: true
  :include_otrunk_examples: false
  :site_url: http://localhost:3000
  :theme: sparks
  :net_logo_package_name: otrunknl4
  :site_district: SPARKS-district
  :runnables_use: browser
  :site_school: SPARKS-school
  :states_and_provinces: 
  - VA
  :default_maven_jnlp: 
    :server: concord
    :family: all-otrunk-snapshot
    :version: snapshot
  :description: ""
  :maven_jnlp_servers: 
  - :path: /dev/org/concord/maven-jnlp/
    :name: concord
    :host: http://jnlp.concord.org
  :use_gse: false
  :active_school_levels: 
  - "2"
  - "3"
  - "4"
  :maven_jnlp_families: 
  - all-otrunk-snapshot
  :help_email: skim@concord.org
