--- 
javascripts: 
- base: 
  - prototype
  - prototype-ui/prototype-ui
  - effects
  - dragdrop
  - controls
  - scriptaculous
  - misc/resizable
  - livepipe/livepipe
  - livepipe/window
  - flotr/excanvas
  - flotr/flotr
  - canvas2image
  - application
  - cookie
  - accordion
  - item_selectable
  - live_validation
  
stylesheets: 
- base: 
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table

- default:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  
- rites:
  - app
  - accordion
  - window/window
  - window/rites
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
    
- itsisu:
  - themes/itsisu/itsisu
  - themes/itsisu/action_menu_tab
  - themes/itsisu/drop_down
  - themes/itsisu/accordion
  - window/window
  - window/itsisu
  - live_validation
  - notes
  - data_table

- smartgraphs:
  - themes/smartgraphs/smartgraphs
  - themes/smartgraphs/action_menu_tab
  - themes/smartgraphs/drop_down
  - themes/smartgraphs/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table

- sglight:
  - themes/sglight/sglight
  - themes/sglight/action_menu_tab
  - themes/sglight/drop_down
  - themes/sglight/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table

- sparks:
  - themes/sparks/sparks
  - themes/sparks/action_menu_tab
  - themes/sparks/drop_down
  - themes/sparks/accordion
  - window/window
  - window/rites
  - live_validation
  - notes
  - data_table

