--- 
javascripts: 
- base: 
  - prototype
  - prototype-ui/prototype-ui
  - effects
  - dragdrop
  - controls
  - scriptaculous
  - misc/resizable
  - livepipe/livepipe
  - livepipe/window
  - flotr/excanvas
  - flotr/flotr
  - canvas2image
  - application
  - cookie
  - accordion
  - item_selectable
  - live_validation
  
stylesheets: 
- base: 
  - app
  - accordion
  - window
  - rites-dialog
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table

- default:
  - app
  - accordion
  - window
  - rites-dialog
  - live_validation
  - action_menu_tab
  - notes
  - drop_down
  - data_table
  
- itsisu:
  - themes/itsisu/itsisu
  - themes/itsisu/action_menu_tab
  - themes/itsisu/drop_down
  - accordion
  - window
  - rites-dialog
  - live_validation
  - notes
  - data_table

