--- 
development: 
  encoding: utf8
  adapter: mysql2
  username: root
  database: portal_development
  password: '*****'
  pool: 5

test:
  encoding: utf8
  adapter: mysql2
  username: root
  database: portal_test
  password: '*****'
  pool: 5

cucumber:
  encoding: utf8
  adapter: mysql2
  username: root
  database: portal_cucumber
  password: '*****'
  pool: 5

staging: 
  encoding: utf8
  adapter: mysql2
  username: root
  database: portal_staging
  password: 
  pool: 5

production: 
  encoding: utf8
  adapter: mysql2
  username: root
  database: portal_production
  password: '*****'
  pool: 5
