development:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  database: risge_development
  username: root
  password:
  pool: 5
  
test:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  database: risge_test
  username: root
  password:
  pool: 5
  
staging:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  database: risge_staging
  username: root
  password:
  pool: 5
  
production:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  database: risge_production
  username: root
  password:
  pool: 5

# Reference to the ITSI database (or a local copy) for use in 
# importing ITSI activities into this RITES instance.
itsi:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: production_itsi_prod
  username: root
  password: 
  asset_url: http://itsidiy.concord.org
  pool: 5

# Reference to the CCPortal database (or a local copy) for use in 
# importing ITSI activities into this RITES instance.
ccportal: 
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  username: root
  database: ccportal
  password: 
  pool: 5
