
#
# SDS configuration file
#

development:
  host: http://sds.local/1
  jnlp_id: 1
  curnit_id: 1
  username: 
  password: 

production:
  host: http://sds.local/1
  jnlp_id: 1
  curnit_id: 1
  username: 
  password: 
