production:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || 'localhost' %>
    port: <%= ENV['SOLR_PORT'] || 8983 %>
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || 'localhost' %>
    port: <%= ENV['SOLR_PORT'] || 8982 %>
    log_level: INFO
    path: /solr/development

test: &TEST
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    auto_commit_after_request: false
cucumber:
  <<: *TEST
